"""add alert archive fields

Revision ID: 0ab2ebd2b00c
Revises: ca4bfe9a1027
Create Date: 2026-06-27 23:54:29.486767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab2ebd2b00c'
down_revision = 'ca4bfe9a1027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_archive',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archive_date', sa.Date(), nullable=False),
    sa.Column('total_alerts', sa.Integer(), nullable=True),
    sa.Column('stream_alerts', sa.Integer(), nullable=True),
    sa.Column('manual_alerts', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('archive_id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false())
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    op.drop_table('alert_archive')
    # ### end Alembic commands ###
