"""add live stream sessions and detections

Revision ID: 145a0656fa1e
Revises: 0ab2ebd2b00c
Create Date: 2026-06-28 13:40:53.512836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145a0656fa1e'
down_revision = '0ab2ebd2b00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_stream_sessions',
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_detections', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('stream_id')
    )
    op.create_table('live_stream_detections',
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('frame_timestamp', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['live_stream_sessions.stream_id'], ),
    sa.PrimaryKeyConstraint('detection_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_stream_detections')
    op.drop_table('live_stream_sessions')
    # ### end Alembic commands ###
