"""Add video_anomaly_timeline table

Revision ID: a4671299c373
Revises: c8d63bbf06d3
Create Date: 2026-06-27 11:20:37.376814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4671299c373'
down_revision = 'c8d63bbf06d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_anomaly_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_anomaly_timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_anomaly_timeline_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_anomaly_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_anomaly_timeline_video_id'))

    op.drop_table('video_anomaly_timeline')
    # ### end Alembic commands ###
