"""add source_type to detection_event

Revision ID: c8d63bbf06d3
Revises: 59b86c9b90da
Create Date: 2026-06-01 18:50:39.022943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d63bbf06d3'
down_revision = '59b86c9b90da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_event', schema=None) as batch_op:
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
